language: objective-c
osx_image: xcode7.3
script:
- set -o pipefail && xcodebuild test -workspace Example/TSSwiftMarkdownParser.xcworkspace -scheme TSSwiftMarkdownParser-Example -sdk iphonesimulator9.3 | xcpretty 
- pod lib lint
