language: objective-c
osx_image: xcode7.3
notifications:
  slack: lyokotech:7AmemNHORB2ShidELPFrYeUO
  email: false
script:
- cd Example
- pod install
- cd ../
- set -o pipefail && xcodebuild test -workspace Example/TSSwiftMarkdownParser.xcworkspace -scheme TSSwiftMarkdownParser-Example -sdk iphonesimulator9.3 | xcpretty 
- pod lib lint
