language: objective-c
osx_image: xcode7.3
notifications:
  slack: lyokotech:7AmemNHORB2ShidELPFrYeUO
  email: false
script:
- set -o pipefail && xcodebuild test -workspace Example/LTMarkdownParser.xcworkspace -scheme LTMarkdownParser-Example -sdk iphonesimulator9.3 | xcpretty
- pod lib lint
